# Generated by Django 5.1.3 on 2025-02-15 23:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='url',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ads'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='article_images'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pictures'),
        ),
    ]
